#+TITLE: Rackspace cloud backup with Heat

*** Brief summary

Rackspace cloud backup configuration resource enables you to select and
backup specific files/folders from a cloud server and schedule backup jobs
using Cloud Orchestration.

**** Prerequisite(s):
Cloud backup agent is installed on the server from where you wanted to backup files/folders

***** Installing cloud backup agent on the server
****** Option-1: If the tenant is a managed operations customer and also the server
was created as part of Heat stack, then pass the following metadata property to
OS::Nova::Server or Rackspace::Cloud::WinServer

#+BEGIN_SRC yaml
  wordpress_server:
    type: "Rackspace::Cloud::WinServer"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      metadata: {build_config: backup_agent_only}
#+END_SRC

****** Option-2: If the tenant is not a managed operations customer or server was not created
as part of the Heat stack creation, then follow links given below to install backup agent.
On Linux server
http://www.rackspace.com/knowledge_center/article/rackspace-cloud-backup-install-the-agent-on-linux

On Windows server
http://www.rackspace.com/knowledge_center/article/rackspace-cloud-backup-install-the-agent-on-windows
On Windows (silent installation)
http://www.rackspace.com/knowledge_center/article/rackspace-cloud-backup-install-the-agent-on-windows-by-using-silent-installation

*** Example template

In the following example template, we will set up a single node wordpress
web application with cloud backup resource.  For the sake of simplicity,
we will not use template parameters in this example.

Start by adding the top-level template sections:

#+BEGIN_SRC yaml
heat_template_version: 2014-10-16

description: |
  Wordpress application with cloud backup.

resources:

outputs:

#+END_SRC

*** Resources section

Add a Rackspace::Cloud::WinServer resource that will create a windows server
and install wordpress web application.

#+BEGIN_SRC yaml
  wordpress_server:
    type: "Rackspace::Cloud::WinServer"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      metadata: {build_config: backup_agent_only}
      user_data:
        str_replace:
          template: |
            $source = "http://download.microsoft.com/download/7/0/4/704CEB4C-9F42-4962-A2B0-5C84B0682C7A/WebPlatformInstaller_amd64_en-US.msi"
            $destination = "webpi.msi"
            $wc = New-Object System.Net.WebClient
            $wc.DownloadFile($source, $destination)
            Start-Process msiexec -ArgumentList "/i webpi.msi /qn"  -NoNewWindow -Wait
            echo DBPassword[@]%dbpassword% DBAdminPassword[@]%dbadminpassword% > test.app
            $tmpprofile = $env:userprofile
            $env:userprofile = "c:\users\administrator"
            $wpicmd = "C:\Program Files\Microsoft\Web Platform Installer\WebPICMD.exe"
            Start-Process $wpicmd -ArgumentList "/Install /Application:Wordpress@test.app /MySQLPassword:%dbadminpassword% /AcceptEULA /Log:.\wpi.log"  -NoNewWindow -Wait
            $env:userprofile = $tmpprofile
          params:
            "%dbpassword%": { get_param: db_password }
            "%dbadminpassword%": { get_param: db_admin_password }
#+END_SRC

**** cloud backup config resource
Add a Rackspace::Cloud::BackupConfig resource that will backup
wordpress application installed at c:\inetpub\wwwroot\wordpress folder.

#+BEGIN_SRC yaml
  rax_backup_config:
    properties:
      BackupConfigurationName: wordpressbackup
      DayOfWeekId: null
      Frequency: Hourly
      StartTimeHour: null
      StartTimeMinute: null
      StartTimeAmPm: null
      HourInterval: 1
      IsActive: true
      Enabled: true
      NotifyFailure: true
      NotifyRecipients: your_email@emailprovider.com
      NotifySuccess: true
      TimeZoneId: Eastern Standard Time
      VersionRetention: 60
      host_ip_address: { get_attr: [rs_windows_server, accessIPv4] }
      Inclusions:
      - {"FilePath": "c:\\inetpub\\wwwroot\\wordpress", "FileItemType": "Folder" }
      - {"FilePath": "c:\\inetpub\\wwwroot\\wordpress", "FileItemType": "Folder" }
    
    type: Rackspace::Cloud::BackupConfig
#+END_SRC

*** Autoscale resources
